### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [daitj/Easycontrol#4]
Hello, would you consider publishing the app on F-Droid please?
See : https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests

**Comment by daitj** [comment]
Yes, this is in my to-do. Check #1 as some of the things are being resolved there first.

I think it might be close for fdroid release as well. In following days I will read about fdroid's inclusion policy and the process. 
I hope they accept a fork like this.

**Comment by shuvashish76** [comment]
Requested for packaging : https://gitlab.com/fdroid/rfp/-/issues/3032

**Comment by licaon-kter** [comment]
move https://github.com/daitj/Easycontrol/tree/main/fastlane/metadata/en-US to `/fastlane/metadata/android/<locale>/` or `/metadata/<locale>/`


ref: https://gitlab.com/-/snippets/1895688

**Comment by daitj** [comment]
@licaon-kter You might know this, this project requires me to build the server apk and copy that to app's resources folder which is done first by 

```
cd easycontrolfork
./gradlew -p server assembleRelease
./gradlew -p server copyRelease
```

then only you can do
```
./gradlew assembleRelease
```

how do i instruct f-droid's build process to do that? I suppose it won't do that automatically because that is not metioned or set anywhere?

**Comment by licaon-kter** [comment]
we're past that :) https://gitlab.com/fdroid/rfp/-/issues/3032#note_2380627495

**Comment by licaon-kter** [comment]
It's a reproducible build, so we need a new release, tagged, built APK

**Comment by daitj** [comment]
well that is done now, so I guess I can close this, thank you for your help @licaon-kter

**Comment by shuvashish76** [comment]
@licaon-kter still requires _a new release, tagged, built APK_ ?

**Comment by licaon-kter** [comment]
@daitj I was ready to include, but... this is Chinese only? If so, please add this info to https://github.com/daitj/Easycontrol/blob/main/fastlane/metadata/android/en-US/full_description.txt so users don't install an app they can't use

**Comment by daitj** [comment]
@licaon-kter My system language was set to Finnish, it defaulted to English. Did you get it in Chinese?

**Comment by licaon-kter** [comment]
like I said, yes

**Comment by shuvashish76** [comment]
Please keep this issue open until available on F-Droid.

**Comment by daitj** [comment]
@licaon-kter I made a new release https://github.com/daitj/Easycontrol/releases/tag/v1.0.4  while ago, which should fix the issue you were experiencing.

**Comment by licaon-kter** [comment]
a bit better, this string is still in  Chinese: https://github.com/daitj/Easycontrol/issues/9

**Comment by licaon-kter** [comment]
but I still don't know what do I need to setup on "the other" device

with ADB ON, won't connect

enabled Wireless, nothing

looked at the exact port in wireless settings

see the link above with the Chinese text

the pics don't help because they have "my" device setup, we need "the other" info too
